/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-04-20 08:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Collections;
import java.util.Comparator;

public final class post_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


        // Define a simple Post class
        public static class Post {
            private int id;
            private String title;
            private String author;
            private String content;
            private Date createdDate;
            
            public Post(int id, String title, String author, String content, Date createdDate) {
                this.id = id;
                this.title = title != null ? title.trim() : "";
                this.author = author != null ? author.trim() : "";
                this.content = content != null ? content : "";
                this.createdDate = createdDate != null ? createdDate : new Date();
            }
            
            public int getId() { return id; }
            public String getTitle() { return title; }
            public String getAuthor() { return author; }
            public String getContent() { return content; }
            public Date getCreatedDate() { return createdDate; }
        }
        
        // Sample posts data (in-memory storage)
        private static List<Post> posts = Collections.synchronizedList(new ArrayList<>());
        private static int nextId = 1;
        
        // Helper function to find post by ID
        public Post findPostById(int id) {
            for (Post post : posts) {
                if (post.getId() == id) {
                    return post;
                }
            }
            return null;
        }
        
        // Helper function to format date
        public String formatDate(Date date, String pattern) {
            if (date == null) return "";
            SimpleDateFormat sdf = new SimpleDateFormat(pattern);
            return sdf.format(date);
        }
        
        // Helper function to get excerpt
        public String getExcerpt(String content, int maxLength) {
            if (content == null) return "";
            if (content.length() <= maxLength) {
                return content;
            }
            // Try to find a space near the cutoff point to avoid cutting words in half
            int cutoff = content.lastIndexOf(' ', maxLength);
            if (cutoff == -1) cutoff = maxLength;
            return content.substring(0, cutoff) + "...";
        }
        
        // Initialize with sample data
        static {
            posts.add(new Post(nextId++, "Getting Started with JSP", "John Doe", 
                "JavaServer Pages (JSP) is a technology that helps software developers create dynamically generated web pages based on HTML, XML, or other document types. JSP is similar to PHP and ASP, but uses the Java programming language.\n\nJSP technology allows Java code and certain pre-defined actions to be interleaved with static web markup content, such as HTML. The resulting page is compiled and executed on the server to deliver a document that can be a complete HTML or XML page or a fragment of a web page that will be integrated into an existing web application.", 
                new Date()));
            
            posts.add(new Post(nextId++, "Understanding Servlets", "Jane Smith", 
                "A servlet is a Java programming language class that is used to extend the capabilities of servers that host applications accessed by means of a request-response programming model. Although servlets can respond to any type of request, they are commonly used to extend the applications hosted by web servers.\n\nServlets are the Java counterpart to non-Java dynamic web content technologies such as PHP and ASP.NET. Servlets are most often used to process or store data submitted by an HTML form, provide dynamic content such as the results of a database query, and manage state information that does not exist in the stateless HTTP protocol.", 
                new Date(System.currentTimeMillis() - 86400000))); // 1 day ago
            
            posts.add(new Post(nextId++, "JSP and JSTL Tips", "Bob Johnson", 
                "JSTL stands for JSP Standard Tag Library. It provides tags that allow developers to perform common tasks like iterations, conditionals, and formatting without writing Java code directly in JSP.\n\nHere are some tips for using JSP and JSTL effectively:\n\n1. Use JSTL tags instead of scriptlets whenever possible\n2. Remember to include the appropriate taglib directives\n3. Use Expression Language (EL) for accessing data\n4. Keep your business logic separate from presentation\n5. Consider using a more modern framework like Spring MVC or JSF for new projects", 
                new Date(System.currentTimeMillis() - 172800000))); // 2 days ago
        }
        
        // Sanitize HTML to prevent XSS attacks
        public String escapeHtml(String input) {
            if (input == null) return "";
            return input.replace("&", "&amp;")
                       .replace("<", "&lt;")
                       .replace(">", "&gt;")
                       .replace("\"", "&quot;")
                       .replace("'", "&#x27;");
        }
    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.Comparator");
    _jspx_imports_classes.add("java.util.Collections");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Simple Blog</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h1, h2 {\r\n");
      out.write("            color: #444;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        a {\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            transition: background-color 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background-color: #0069d9;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-danger {\r\n");
      out.write("            background-color: #dc3545;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-danger:hover {\r\n");
      out.write("            background-color: #c82333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nav-links {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post-card {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post-meta {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post-excerpt {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .post-content {\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            line-height: 1.8;\r\n");
      out.write("            white-space: pre-line;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group input,\r\n");
      out.write("        .form-group textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .inline-form {\r\n");
      out.write("            display: inline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-success {\r\n");
      out.write("            background-color: #d4edda;\r\n");
      out.write("            color: #155724;\r\n");
      out.write("            border: 1px solid #c3e6cb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-danger {\r\n");
      out.write("            background-color: #f8d7da;\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("            border: 1px solid #f5c6cb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .post-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .post-actions {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .btn {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

        // Get session message if exists and clear it
        String message = (String) session.getAttribute("message");
        String messageType = (String) session.getAttribute("messageType");
        session.removeAttribute("message");
        session.removeAttribute("messageType");
        
        try {
            // Process form submissions
            String action = request.getParameter("action");
            
            if ("create".equals(action) || "update".equals(action)) {
                String title = request.getParameter("title");
                String author = request.getParameter("author");
                String content = request.getParameter("content");
                
                // Simple validation
                if (title == null || title.trim().isEmpty() || 
                    author == null || author.trim().isEmpty() || 
                    content == null || content.trim().isEmpty()) {
                    throw new IllegalArgumentException("All fields are required");
                }
                
                if ("create".equals(action)) {
                    // Create new post
                    posts.add(new Post(nextId++, title, author, content, new Date()));
                    session.setAttribute("message", "Post created successfully!");
                    session.setAttribute("messageType", "success");
                } else {
                    // Update existing post
                    int id = Integer.parseInt(request.getParameter("id"));
                    Post existingPost = findPostById(id);
                    
                    if (existingPost != null) {
                        synchronized(posts) {
                            for (int i = 0; i < posts.size(); i++) {
                                Post post = posts.get(i);
                                if (post.getId() == id) {
                                    posts.set(i, new Post(id, title, author, content, post.getCreatedDate()));
                                    break;
                                }
                            }
                        }
                        session.setAttribute("message", "Post updated successfully!");
                        session.setAttribute("messageType", "success");
                    } else {
                        session.setAttribute("message", "Post not found!");
                        session.setAttribute("messageType", "danger");
                    }
                }
                
                // Redirect to avoid form resubmission
                response.sendRedirect(request.getContextPath() + "/index.jsp");
                return;
            } else if ("delete".equals(action)) {
                // Delete post
                int id = Integer.parseInt(request.getParameter("id"));
                boolean removed = false;
                
                synchronized(posts) {
                    for (int i = 0; i < posts.size(); i++) {
                        if (posts.get(i).getId() == id) {
                            posts.remove(i);
                            removed = true;
                            break;
                        }
                    }
                }
                
                if (removed) {
                    session.setAttribute("message", "Post deleted successfully!");
                    session.setAttribute("messageType", "success");
                } else {
                    session.setAttribute("message", "Post not found!");
                    session.setAttribute("messageType", "danger");
                }
                
                // Redirect to avoid form resubmission
                response.sendRedirect(request.getContextPath() + "/index.jsp");
                return;
            }
            
            // Handle view mode
            String view = request.getParameter("view");
            String postIdParam = request.getParameter("id");
            
            if ("new".equals(view)) {
                // Show new post form
    
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <h1>Create New Blog Post</h1>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"nav-links\">\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"btn\">← Back to Posts</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if (message != null && !message.isEmpty()) { 
      out.write("\r\n");
      out.write("                        <div class=\"alert alert-");
      out.print( messageType );
      out.write("\">\r\n");
      out.write("                            ");
      out.print( escapeHtml(message) );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"create\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"title\">Title</label>\r\n");
      out.write("                            <input type=\"text\" id=\"title\" name=\"title\" maxlength=\"200\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"author\">Author</label>\r\n");
      out.write("                            <input type=\"text\" id=\"author\" name=\"author\" maxlength=\"100\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"content\">Content</label>\r\n");
      out.write("                            <textarea id=\"content\" name=\"content\" rows=\"10\" required></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-actions\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\">Save</button>\r\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"btn\">Cancel</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("    ");

            } else if ("edit".equals(view) && postIdParam != null) {
                // Show edit post form
                try {
                    int postId = Integer.parseInt(postIdParam);
                    Post postToEdit = findPostById(postId);
                    
                    if (postToEdit != null) {
    
      out.write("\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <h1>Edit Blog Post</h1>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"nav-links\">\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"btn\">← Back to Posts</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            ");
 if (message != null && !message.isEmpty()) { 
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-");
      out.print( messageType );
      out.write("\">\r\n");
      out.write("                                    ");
      out.print( escapeHtml(message) );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" method=\"post\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"action\" value=\"update\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( postToEdit.getId() );
      out.write("\">\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"title\">Title</label>\r\n");
      out.write("                                    <input type=\"text\" id=\"title\" name=\"title\" value=\"");
      out.print( escapeHtml(postToEdit.getTitle()) );
      out.write("\" maxlength=\"200\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"author\">Author</label>\r\n");
      out.write("                                    <input type=\"text\" id=\"author\" name=\"author\" value=\"");
      out.print( escapeHtml(postToEdit.getAuthor()) );
      out.write("\" maxlength=\"100\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"content\">Content</label>\r\n");
      out.write("                                    <textarea id=\"content\" name=\"content\" rows=\"10\" required>");
      out.print( escapeHtml(postToEdit.getContent()) );
      out.write("</textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"form-actions\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn\">Save</button>\r\n");
      out.write("                                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"btn\">Cancel</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("    ");

                    } else {
                        // Post not found, redirect to posts list
                        session.setAttribute("message", "Post not found!");
                        session.setAttribute("messageType", "danger");
                        response.sendRedirect(request.getContextPath() + "/index.jsp");
                        return;
                    }
                } catch (NumberFormatException e) {
                    // Invalid ID format, redirect to posts list
                    session.setAttribute("message", "Invalid post ID!");
                    session.setAttribute("messageType", "danger");
                    response.sendRedirect(request.getContextPath() + "/index.jsp");
                    return;
                }
            } else if (postIdParam != null) {
                // Show single post view
                try {
                    int postId = Integer.parseInt(postIdParam);
                    Post postToView = findPostById(postId);
                    
                    if (postToView != null) {
    
      out.write("\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"nav-links\">\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"btn\">← Back to Posts</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            ");
 if (message != null && !message.isEmpty()) { 
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-");
      out.print( messageType );
      out.write("\">\r\n");
      out.write("                                    ");
      out.print( escapeHtml(message) );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            <article class=\"post\">\r\n");
      out.write("                                <h1>");
      out.print( escapeHtml(postToView.getTitle()) );
      out.write("</h1>\r\n");
      out.write("                                <div class=\"post-meta\">\r\n");
      out.write("                                    By ");
      out.print( escapeHtml(postToView.getAuthor()) );
      out.write(" on ");
      out.print( formatDate(postToView.getCreatedDate(), "MMMM dd, yyyy") );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"post-content\">\r\n");
      out.write("                                    ");
      out.print( escapeHtml(postToView.getContent()) );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"post-actions\">\r\n");
      out.write("                                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp?view=edit&id=");
      out.print( postToView.getId() );
      out.write("\" class=\"btn\">Edit</a>\r\n");
      out.write("                                    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" method=\"post\" class=\"inline-form\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( postToView.getId() );
      out.write("\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-danger\" onclick=\"return confirm('Are you sure you want to delete this post?')\">Delete</button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </article>\r\n");
      out.write("                        </div>\r\n");
      out.write("    ");

                    } else {
                        // Post not found, redirect to posts list
                        session.setAttribute("message", "Post not found!");
                        session.setAttribute("messageType", "danger");
                        response.sendRedirect(request.getContextPath() + "/index.jsp");
                        return;
                    }
                } catch (NumberFormatException e) {
                    // Invalid ID format, redirect to posts list
                    session.setAttribute("message", "Invalid post ID!");
                    session.setAttribute("messageType", "danger");
                    response.sendRedirect(request.getContextPath() + "/index.jsp");
                    return;
                }
            } else {
                // Show posts list (default view)
                // Sort posts by date (most recent first)
                List<Post> sortedPosts = new ArrayList<>(posts);
                Collections.sort(sortedPosts, new Comparator<Post>() {
                    public int compare(Post p1, Post p2) {
                        return p2.getCreatedDate().compareTo(p1.getCreatedDate());
                    }
                });
    
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <h1>Blog Posts</h1>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"nav-links\">\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp?view=new\" class=\"btn\">Create New Post</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if (message != null && !message.isEmpty()) { 
      out.write("\r\n");
      out.write("                        <div class=\"alert alert-");
      out.print( messageType );
      out.write("\">\r\n");
      out.write("                            ");
      out.print( escapeHtml(message) );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if (sortedPosts.isEmpty()) { 
      out.write("\r\n");
      out.write("                        <p>No posts available. Create your first blog post!</p>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"post-grid\">\r\n");
      out.write("                            ");
 for (Post post : sortedPosts) { 
      out.write("\r\n");
      out.write("                                <div class=\"post-card\">\r\n");
      out.write("                                    <h2><a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp?id=");
      out.print( post.getId() );
      out.write('"');
      out.write('>');
      out.print( escapeHtml(post.getTitle()) );
      out.write("</a></h2>\r\n");
      out.write("                                    <p class=\"post-meta\">\r\n");
      out.write("                                        By ");
      out.print( escapeHtml(post.getAuthor()) );
      out.write(" on ");
      out.print( formatDate(post.getCreatedDate(), "MMM dd, yyyy") );
      out.write("\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <p class=\"post-excerpt\">");
      out.print( escapeHtml(getExcerpt(post.getContent(), 150)) );
      out.write("</p>\r\n");
      out.write("                                    <div class=\"post-actions\">\r\n");
      out.write("                                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp?id=");
      out.print( post.getId() );
      out.write("\" class=\"btn\">Read More</a>\r\n");
      out.write("                                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp?view=edit&id=");
      out.print( post.getId() );
      out.write("\" class=\"btn\">Edit</a>\r\n");
      out.write("                                        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" method=\"post\" class=\"inline-form\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( post.getId() );
      out.write("\">\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-danger\" onclick=\"return confirm('Are you sure you want to delete this post?')\">Delete</button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("    ");

            }
        } catch (NumberFormatException e) {
            // Handle number format exception
            session.setAttribute("message", "Invalid ID format!");
            session.setAttribute("messageType", "danger");
            response.sendRedirect(request.getContextPath() + "/index.jsp");
            return;
        } catch (Exception e) {
            // Handle other exceptions
            session.setAttribute("message", "Error: " + e.getMessage());
            session.setAttribute("messageType", "danger");
            response.sendRedirect(request.getContextPath() + "/index.jsp");
            return;
        }
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
